# Generated by Django 5.1.3 on 2024-11-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='percentage',
            new_name='weight',
        ),
    ]
