# Generated by Django 5.1.3 on 2024-12-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_stock_is_afa'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('afaPrice', models.DecimalField(decimal_places=4, max_digits=6)),
                ('spPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
